### ISSUE TITLE
XLua documentation

### ISSUE THREAD

**Issue by vranki** [X-Plane/XLua#1]
I can't find any documentation on how to use XLua anywhere. Does it even exist?

Someone else seems to have the same issue:
https://questions.x-plane.com/17059/documentation-for-xlua-plugin

Github wiki or X-Plane SDK docs would be a good place for the docs.

**Comment by JDeeth** [comment]
There's this post on the x-plane.org forums which might be the closest
thing we've got to a manual:
https://forums.x-plane.org/index.php?/forums/topic/154351-xlua-scripting/&tab=comments#comment-1460039

**Comment by Danita** [comment]
There is now proper documentation on the README.md file at the root of the repo.
