### ISSUE TITLE
Cannot run r120r1

### ISSUE THREAD

**Issue by mgateno** [X-Plane/XLua#11]
I just tried upgrading to r120r1. My plane (C90B JP_Evo) loads two modules: C90_sys and C90_gpws. Only C90_gpws loads accoring to the log.txt file. The other module has a correct name structure (works perfectly with r1) but does not load. Is there anything that needs to be done besides copying the binaries and init files in the plugins/xlua directory? BTW.. the diagram of the directory structure you have in the readme seems to be wrong?

**Comment by Danita** [comment]
I just fixed the directory structure diagram on the docs. As for usage help, you'd better be off asking on the XLua forums on X-Plane.org.

**Comment by JT8D-17** [comment]
This was issue #4 at work and also affected the default King Air C90B after an upgrade to XLua 1.1+.

The solution was pre-declaring "C90" as a raw table in c90_sys.lua:
> raw_table("C90")
> C90	= {}

See here: https://forums.x-plane.org/index.php?/forums/topic/263896-xlua-12-is-out/&do=findComment&comment=2341204
