### ISSUE TITLE
No Errors Shown in Developer Console 

### ISSUE THREAD

**Issue by Andywmm9** [X-Plane/XLua#3]
Any lua errors should be shown in the xplane development console.   I haven’t found a way to display any error messages.

**Comment by jmartorell** [comment]
Launch X-Plane from the Terminal in Linux or Mac.
In Windows, you can use git-bash, but you can also use the command prompt. Redirect the output using `>` and you'll get a log in the file. See the [Xlua trhead in X-plane.org forums](https://forums.x-plane.org/index.php?/forums/topic/154351-xlua-scripting/&page=3&tab=comments#comment-1666330) for more information.
