### ISSUE TITLE
Strange issue with global arrays

### ISSUE THREAD

**Issue by Danita** [X-Plane/XLua#4]
Look at this short test script:

```lua

msg_data = {
    { id = 'bla', duration = 350 },
    { id = 'asdas', duration = 440 },
    { id = 'qwqwe', duration = 360 },
    { id = 'zxczxc', duration = 280 },
    { id = 'lala', duration = 400 },
}

message_count_at_load = 0
message_count_at_init = 0

for k, v in pairs(msg_data) do
    message_count_at_load = message_count_at_load + 1
end

print("=== LOAD ===")
print("message count at script load time:", message_count_at_load)

function initialize()
    print("=== INIT ===")
    for k, v in pairs(msg_data) do
        message_count_at_init = message_count_at_init + 1
    end
    print("message count at aircraft load time:", message_count_at_init)
end

function aircraft_load()
    initialize()
end
```

The output is:

```
... (clipped)
Running scripts/B738.fire/B738.fire.lua
Running scripts/B738.gear/B738.gear.lua
Running scripts/B738.glaresheild/B738.glaresheild.lua
Running scripts/B738.test/B738.test.lua
=== LOAD ===
message count at script load time:      0
Running scripts/B738.LATLON/B738.LATLON.lua
Running scripts/B738.lighting/B738.lighting.lua
... (clipped)
=== INIT ===
message count at aircraft load time:    0
```

As you can see, the count always return zero, as if `pairs` was not working correctly.
I've found that:

* If you access a member by index, the array element is indeed returned correctly.
* The result doesn't change if I use `pairs` or `ipairs`.
* The count does indeed work if I declare `msg_data` as `local`.

Any ideas?

**Comment by Danita** [comment]
For the record, the bug is confirmed by @bsupnik and at the time a possible workaround is using local arrays instead of globals.

**Comment by JGregory** [comment]
I'm not sure this is a bug in XLua.  I ran the test script provided and the results were as expected.  See the following output...

```
Running scripts/c172_test/c172_test.lua
Using STP as debugger.
=== LOAD ===
message count at script load time:	5
BAD GAMMA: Aircraft/JGX/_JGX_XLua_test/_JGX_test_prop.png
parse_voice_pack: Resources/default scenery/1200 atc data/voices/default pilot/default_pilot.voc: 1462307 usec
=== INIT ===
message count at aircraft load time:	5
BAD GAMMA: Aircraft/JGX/_JGX_XLua_test/_JGX_test_prop.png
```

**Comment by Danita** [comment]
@JGregory you can try yourself, the script I provided is part of the B738 gpws script :)

**Comment by JGregory** [comment]
> @JGregory you can try yourself, the script I provided is part of the B738 gpws script :)

@Danita - When I run the B738 I get a message count of nil on aircraft_load, and a message count of (29) on flight_start.  That is correct behavior.  Your initialize function that creates the table of messages is run in the flight_start callback, which runs after the aircraft_load callback. Therefore the count is nil until flight_start runs the initialize function.

**Comment by Danita** [comment]
Well it certainly didn't do that when I reported the bug, that's why I reported it. I'm glad it's fixed now.

**Comment by Danita** [comment]
This bug doesn't seem to reproduce on Macs.

**Comment by Danita** [comment]
There is now the `raw_table` function in 1.1.0 that allows you to create a table that is not "enhanced" with the automagical wiring of datarefs. Making the `msg_data` a raw table in this case solves the bug.

**Comment by JT8D-17** [comment]
I'm making use of a lot of global tables that get passed to functions stored in submodules in an XLua module and this behavior did definitely not occur in release 1.0.0 and was introduced in 1.1.0. The entire module has become essentially unusable without some major rework.

Is this something peculiar to LuaJIT or a regression in XLua?

That "raw_table" workaround produces a segfault.

```
XluaUtils_Config_Vars = {
{"XLUAUTILS"},
{"DebugOutput",0},
{"DebugWindow",0},
{"DebugWindowPos",200,600,600,200}, -- left, top, right, bottom
}

raw_table(XluaUtils_Config_Vars)
```

**Comment by JGregory** [comment]
> I'm making use of a lot of global tables that get passed to functions stored in submodules in an XLua module and this behavior did definitely not occur in release 1.0.0 and was introduced in 1.1.0. The entire module has become essentially unusable without some major rework.
> 
> Is this something peculiar to LuaJIT or a regression in XLua?
> 
> That "raw_table" workaround produces a segfault.
> 
> ```
> XluaUtils_Config_Vars = {
> {"XLUAUTILS"},
> {"DebugOutput",0},
> {"DebugWindow",0},
> {"DebugWindowPos",200,600,600,200}, -- left, top, right, bottom
> }
> 
> raw_table(XluaUtils_Config_Vars)
> ```

Place the "raw_table" declaration in the your script before the table creator.

**Comment by JT8D-17** [comment]
```
raw_table(XluaUtils_Config_Vars)
XluaUtils_Config_Vars = {
{"XLUAUTILS"},
{"DebugOutput",0},
{"DebugWindow",0},
{"DebugWindowPos",200,600,600,200}, -- left, top, right, bottom
}
```

This also does not work.
 
For what it's worth, this is the project in question: https://github.com/JT8D-17/XLua-Utils-for-X-Plane
It does not work at all in 1.1/1.2 due to the global/local scoping regression.


- Edit:

I'm trying to apply fixes at the moment, but it feels like going around with a bucket of water in a burning house.

**Comment by JGregory** [comment]
The raw_table call needs to include quotes....   raw_table('XluaUtils_Config_Vars')

I can't really test any of the rest of your script because I don't have the other scripts/source... but... when I comment that stuff out I can load your table without any errors

**Comment by JT8D-17** [comment]
The quotes work. Somebody should update the FAQ section of XLua's readme to reflect that and add the bit of info that "raw_table" declaration has to be done prior to table initialization.

The example I've posted is part of my "XLua Utils" project, which I've successfully rewriten for XLua 1.1+ compliance (it still works in XLua 1.0). I'm still a bit mad that this was necessary in the first place.

**Comment by JT8D-17** [comment]
I've discussed the issue and possible solutions in a forum post on the Org:

https://forums.x-plane.org/index.php?/forums/topic/263896-xlua-12-is-out/&do=findComment&comment=2336764

**Comment by JGregory** [comment]
The tables are definitely global once you use ‘raw_table’. 

The issue that you are seeing is a matter of timing and scope.

If you move your print statements like this….

function flight_start()
	print("Main table length is "..GetLength(testtable))
	print("Submodule table length is "..GetLength(submoduletesttable))
end

It works as expected.

And.. the flight_start callback can be in any of the modules.
